### ISSUE TITLE
Add project: Ask me Anything (AMA)

### ISSUE THREAD

**Issue by apugoneappu** [jrieke/best-of-streamlit#14]
**Project details:**

- Project Name: Ask me anything
- Github URL: https://github.com/apugoneappu/ask_me_anything
- Category: ml, cv, nlp 
- License:
- Package Managers: 

**Additional context:**
- Project website/demo: https://www.apoorvesinghal.com/vqa

This is a Visual Question Answering tool. You can ask a question about images, and the VQA system will answer them. Additionally, I have also visualised the regions of the image that the system looks at to answer. We can also see the words of the question that the system focuses on.

**Comment by jrieke** [comment]
Great app, thanks for reporting! I added it to the projects list and it will show up in the gallery with the next regular update on Monday :) I added it to CV for now, let me know if you'd rather like to have it in the NLP category.

**Comment by apugoneappu** [comment]
Thanks for this kind service to the Streamlit community, Johannes! CV is good :)
