### ISSUE TITLE
Add project: Covid-19: Tracking of vaccines and infections in Italy

### ISSUE THREAD

**Issue by francesconazzaro** [jrieke/best-of-streamlit#15]
**Project details:**

- Project Name: Covid-19: Tracking of vaccines and infections in Italy
- Github URL: https://github.com/francesconazzaro/covid19-portal
- App URL (if it's deployed): https://covid19-portal.herokuapp.com/
- Category: sci-tech

**Additional context:**

Analyse data for COVID-19 vaccines administrations and COVID-19 infections in Italy.

**Comment by jrieke** [comment]
Hey @francesconazzaro, thanks so much for the PR! I just made the title a bit shorter (want to keep all titles in one line), hope that's ok, and merged. It will appear in the list with the next regular update on Monday :)

**Comment by francesconazzaro** [comment]
no problem, thank you! :)
